// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZkDLNJWUd9-KGsRuYtlw3o5WkUWWlveU',
    appId: '1:30431010037:web:9f474b73a4bcabcc38f9bc',
    messagingSenderId: '30431010037',
    projectId: 'inventory-app-499a3',
    authDomain: 'inventory-app-499a3.firebaseapp.com',
    storageBucket: 'inventory-app-499a3.firebasestorage.app',
    measurementId: 'G-B4GF0YRHYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD64rlYpnHb00uDuWvKg8XITlL16LjGRjA',
    appId: '1:30431010037:android:f00568e7c28dbb6638f9bc',
    messagingSenderId: '30431010037',
    projectId: 'inventory-app-499a3',
    storageBucket: 'inventory-app-499a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GxG4Kw9-6y6jCqaWhUuAkymMcDMuFWI',
    appId: '1:30431010037:ios:d22dfe9b77e14f7138f9bc',
    messagingSenderId: '30431010037',
    projectId: 'inventory-app-499a3',
    storageBucket: 'inventory-app-499a3.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GxG4Kw9-6y6jCqaWhUuAkymMcDMuFWI',
    appId: '1:30431010037:ios:d22dfe9b77e14f7138f9bc',
    messagingSenderId: '30431010037',
    projectId: 'inventory-app-499a3',
    storageBucket: 'inventory-app-499a3.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZkDLNJWUd9-KGsRuYtlw3o5WkUWWlveU',
    appId: '1:30431010037:web:bafbe3d61590140e38f9bc',
    messagingSenderId: '30431010037',
    projectId: 'inventory-app-499a3',
    authDomain: 'inventory-app-499a3.firebaseapp.com',
    storageBucket: 'inventory-app-499a3.firebasestorage.app',
    measurementId: 'G-C342TQVC5L',
  );
}
